<a href="https://colab.research.google.com/github/honestfarmer-cod/greends-ipython/blob/Assigments_honestfarmer/Assig03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
df = pd.read_csv(f'{path}/kiva_loans.csv')
print(df)

             id  funded_amount  loan_amount             activity  \
0        653051          300.0        300.0  Fruits & Vegetables
1        653053          575.0        575.0             Rickshaw
2        653068          150.0        150.0       Transportation
3        653063          200.0        200.0           Embroidery
4        653084          400.0        400.0           Milk Sales
...         ...            ...          ...                  ...
671200  1340323            0.0         25.0            Livestock
671201  1340316           25.0         25.0            Livestock
671202  1340334            0.0         25.0                Games
671203  1340338            0.0         25.0            Livestock
671204  1340339            0.0         25.0            Livestock

                sector                                                use  \
0                 Food            To buy seasonal, fresh fruits to sell.
1       Transportation  to repair and maintain the auto rickshaw used ...
2       Transportation  To repair their old cycle-van and buy another ...
3                 Arts  to purchase an embroidery machine and a variet...
4                 Food                           to purchase one buffalo.
...                ...                                                ...
671200     Agriculture  [True, u'para compara: cemento, arenya y ladri...
671201     Agriculture  [True, u'to start a turducken farm.'] - this l...
671202   Entertainment                                                NaN
671203     Agriculture  [True, u'to start a turducken farm.'] - this l...
671204     Agriculture  [True, u'to start a turducken farm.'] - this l...

       country_code   country        region currency  partner_id  \
0                PK  Pakistan        Lahore      PKR       247.0
1                PK  Pakistan        Lahore      PKR       247.0
2                IN     India     Maynaguri      INR       334.0
3                PK  Pakistan        Lahore      PKR       247.0
4                PK  Pakistan  Abdul Hakeem      PKR       245.0
...             ...       ...           ...      ...         ...
671200           PY  Paraguay    Concepción      USD        58.0
671201           KE     Kenya           NaN      KES       138.0
671202           KE     Kenya           NaN      KES       138.0
671203           KE     Kenya           NaN      KES       138.0
671204           KE     Kenya           NaN      KES       138.0

                      posted_time             disbursed_time  \
0       2014-01-01 06:12:39+00:00  2013-12-17 08:00:00+00:00
1       2014-01-01 06:51:08+00:00  2013-12-17 08:00:00+00:00
2       2014-01-01 09:58:07+00:00  2013-12-17 08:00:00+00:00
3       2014-01-01 08:03:11+00:00  2013-12-24 08:00:00+00:00
4       2014-01-01 11:53:19+00:00  2013-12-17 08:00:00+00:00
...                           ...                        ...
671200  2017-07-25 16:55:34+00:00  2017-07-25 07:00:00+00:00
671201  2017-07-25 06:14:08+00:00  2017-07-24 07:00:00+00:00
671202  2017-07-26 00:02:07+00:00  2017-07-25 07:00:00+00:00
671203  2017-07-26 06:12:55+00:00  2017-07-25 07:00:00+00:00
671204  2017-07-26 06:31:46+00:00  2017-07-25 07:00:00+00:00

                      funded_time  term_in_months  lender_count  \
0       2014-01-02 10:06:32+00:00            12.0            12
1       2014-01-02 09:17:23+00:00            11.0            14
2       2014-01-01 16:01:36+00:00            43.0             6
3       2014-01-01 13:00:00+00:00            11.0             8
4       2014-01-01 19:18:51+00:00            14.0            16
...                           ...             ...           ...
671200                        NaN            13.0             0
671201  2017-07-26 02:09:43+00:00            13.0             1
671202                        NaN            13.0             0
671203                        NaN            13.0             0
671204                        NaN            13.0             0

                                tags borrower_genders repayment_interval  \
0                                NaN           female          irregular
1                                NaN   female, female          irregular
2       user_favorite, user_favorite           female             bullet
3                                NaN           female          irregular
4                                NaN           female            monthly
...                              ...              ...                ...
671200                           NaN           female            monthly
671201                           NaN           female            monthly
671202                           NaN              NaN            monthly
671203                           NaN           female            monthly
671204                           NaN           female            monthly

              date
0       2014-01-01
1       2014-01-01
2       2014-01-01
3       2014-01-01
4       2014-01-01
...            ...
671200  2017-07-25
671201  2017-07-25
671202  2017-07-26
671203  2017-07-26
671204  2017-07-26

[671205 rows x 20 columns]

In [10]:
#1. Select rows using string methods (e.g. .isin) and numerical conditions
df[(df['sector'].isin(['Agriculture'])) & (df['loan_amount'] > 1000)]

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
85,653175,3175.0,3175.0,Agriculture,Agriculture,"To purchase standard quality seeds, fertilizer...",IN,India,"Balipatna, Odisha",INR,241.0,2014-01-02 06:43:17+00:00,2013-12-03 08:00:00+00:00,2014-01-14 21:57:40+00:00,43.0,97,"#Supporting Family, #Vegan, #Fabrics, #Parent,...","female, female, female, female, female, female...",bullet,2014-01-02
130,653206,1500.0,1500.0,Cattle,Agriculture,To buy another cow for her husband to raise an...,KH,Cambodia,Khsach Kandal district,USD,61.0,2014-01-02 07:57:12+00:00,2013-12-18 08:00:00+00:00,2014-01-03 11:34:47+00:00,22.0,54,NaN,female,monthly,2014-01-02
165,653403,2850.0,2850.0,Poultry,Agriculture,to buy chickens.,GT,Guatemala,NaN,GTQ,113.0,2014-01-02 18:21:41+00:00,2013-12-09 08:00:00+00:00,2014-01-03 18:47:01+00:00,12.0,97,"volunteer_pick, user_favorite","female, female, female, female, female, female...",monthly,2014-01-02
182,653132,1225.0,1225.0,Dairy,Agriculture,to purchase large amount of dairy products fro...,MN,Mongolia,Govi-Altai,MNT,116.0,2014-01-02 02:55:07+00:00,2013-12-04 08:00:00+00:00,2014-01-02 08:54:07+00:00,18.0,49,#Parent,female,monthly,2014-01-02
223,653156,2125.0,2125.0,Animal Sales,Agriculture,To purchase more goat kids,IN,India,"Balipatna, Odisha",INR,241.0,2014-01-02 05:27:48+00:00,2013-12-02 08:00:00+00:00,2014-01-03 11:47:12+00:00,43.0,51,NaN,"female, female, female, female, female, female...",bullet,2014-01-02
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
671100,1338385,50.0,1500.0,Dairy,Agriculture,to buy a dairy cow.,EC,Ecuador,San Gabriel,USD,188.0,2017-07-12 15:05:03+00:00,2017-07-11 07:00:00+00:00,NaN,38.0,2,"#Animals, #Biz Durable Asset, #Repeat Borrower...",male,monthly,2017-07-12
671111,1339254,0.0,1300.0,Farming,Agriculture,to buy compost and fertilizers and to hire wor...,EC,Ecuador,San Gabriel,USD,188.0,2017-07-13 13:50:16+00:00,2017-07-12 07:00:00+00:00,NaN,17.0,0,"#Job Creator, #Repeat Borrower",male,monthly,2017-07-13
671112,1339237,0.0,1300.0,Pigs,Agriculture,"to buy pigs, potatoes, and balanced feed.",EC,Ecuador,San Gabriel,USD,188.0,2017-07-13 13:17:01+00:00,2017-07-12 07:00:00+00:00,NaN,17.0,0,"#Single Parent, #Animals, #Parent",female,monthly,2017-07-13
671143,1339701,125.0,1175.0,Farming,Agriculture,to purchase seeds and fertilizer for his green...,UA,Ukraine,Gladkovka,UAH,26.0,2017-07-14 04:53:04+00:00,2017-07-10 07:00:00+00:00,NaN,14.0,5,"user_favorite, user_favorite, #Parent, #Repair...",male,monthly,2017-07-14
671144,1339679,175.0,1950.0,Farming,Agriculture,to purchase planting stock and fertilizers.,UA,Ukraine,Gladkovka,UAH,26.0,2017-07-14 04:18:14+00:00,2017-07-11 07:00:00+00:00,NaN,14.0,7,"#Parent, #Vegan, #Woman Owned Biz, user_favorite",female,monthly,2017-07-14

In [11]:
#2. Sort table using one column
display (df.sort_values(by='date', ascending=False))

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
671204,1340339,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:31:46+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26
671203,1340338,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:12:55+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26
671202,1340334,0.0,25.0,Games,Entertainment,NaN,KE,Kenya,NaN,KES,138.0,2017-07-26 00:02:07+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,NaN,monthly,2017-07-26
671195,1340329,0.0,50.0,Livestock,Agriculture,Edited loan use in english.,GH,Ghana,Dansoman,GHS,231.0,2017-07-25 22:40:59+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,"female, female",monthly,2017-07-25
671189,1340315,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-25 05:59:38+00:00,2017-07-24 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29,653073,250.0,250.0,Farming,Agriculture,to purchase potato seeds and fertilizer for fa...,IN,India,Dhupguri,INR,334.0,2014-01-01 11:09:26+00:00,2013-12-19 08:00:00+00:00,2014-01-01 21:47:05+00:00,43.0,10,NaN,female,bullet,2014-01-01
28,653071,125.0,125.0,Farming,Agriculture,to purchase potato seeds and fertilizers for g...,IN,India,Maynaguri,INR,334.0,2014-01-01 10:35:20+00:00,2013-12-17 08:00:00+00:00,2014-01-01 16:06:47+00:00,43.0,5,NaN,female,bullet,2014-01-01
27,653056,475.0,475.0,Rickshaw,Transportation,to cover the cost of repairing rickshaw,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 07:20:09+00:00,2013-12-24 08:00:00+00:00,2014-01-01 20:26:48+00:00,12.0,17,NaN,female,irregular,2014-01-01
26,653069,250.0,250.0,Construction Supplies,Construction,to purchase stones for starting a business sup...,IN,India,Maynaguri,INR,334.0,2014-01-01 10:04:17+00:00,2013-12-10 08:00:00+00:00,2014-01-01 22:12:43+00:00,43.0,10,"user_favorite, user_favorite",female,bullet,2014-01-01
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01

In [15]:
#2 Sort table using multiple columns
display (df.sort_values(by=['posted_time', 'loan_amount'], ascending=False ))

,id,funded_amount,loan_amount,activity,sector,use,country_code,country,region,currency,partner_id,posted_time,disbursed_time,funded_time,term_in_months,lender_count,tags,borrower_genders,repayment_interval,date
671204,1340339,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:31:46+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26
671203,1340338,0.0,25.0,Livestock,Agriculture,"[True, u'to start a turducken farm.'] - this l...",KE,Kenya,NaN,KES,138.0,2017-07-26 06:12:55+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,female,monthly,2017-07-26
671202,1340334,0.0,25.0,Games,Entertainment,NaN,KE,Kenya,NaN,KES,138.0,2017-07-26 00:02:07+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,NaN,monthly,2017-07-26
671193,1340333,0.0,125.0,Livestock,Agriculture,Pretend the flagged issue was addressed by KC.,MX,Mexico,Iztacalco,MXN,294.0,2017-07-25 23:45:38+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,"female, female",monthly,2017-07-25
671194,1340332,0.0,25.0,Livestock,Agriculture,Kiva Coordinator fixed issue loan (no longer v...,KE,Kenya,NaN,KES,138.0,2017-07-25 23:29:57+00:00,2017-07-25 07:00:00+00:00,NaN,13.0,0,NaN,"female, female",monthly,2017-07-25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
0,653051,300.0,300.0,Fruits & Vegetables,Food,"To buy seasonal, fresh fruits to sell.",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:12:39+00:00,2013-12-17 08:00:00+00:00,2014-01-02 10:06:32+00:00,12.0,12,NaN,female,irregular,2014-01-01
22,653050,575.0,575.0,Clothing Sales,Clothing,To buy winter clothing to sell,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 06:05:17+00:00,2013-12-17 08:00:00+00:00,2014-01-02 23:56:08+00:00,12.0,20,NaN,"female, female",irregular,2014-01-01
43,653049,250.0,250.0,Shoe Sales,Retail,To buy women's shoes to sell,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 05:54:34+00:00,2013-12-17 08:00:00+00:00,2014-01-02 15:21:21+00:00,12.0,8,NaN,female,irregular,2014-01-01
9,653048,625.0,625.0,Food Production/Sales,Food,"to buy a stall, gram flour, ketchup, and coal ...",PK,Pakistan,Lahore,PKR,247.0,2014-01-01 05:41:03+00:00,2013-12-17 08:00:00+00:00,2014-01-03 15:45:04+00:00,11.0,24,NaN,female,irregular,2014-01-01
35,653047,2225.0,2225.0,Personal Products Sales,Retail,to buy hair oils to sell.,PK,Pakistan,Lahore,PKR,247.0,2014-01-01 04:49:26+00:00,2013-12-17 08:00:00+00:00,2014-01-19 16:39:37+00:00,11.0,58,"#Parent, #Repeat Borrower, user_favorite","female, female, female, female, female, female...",irregular,2014-01-01

In [19]:
#3. Group and aggregate rows with "groupby"
display(df[df['sector'] == 'Agriculture'].groupby('sector')['loan_amount'].sum().reset_index())

        sector  loan_amount
0  Agriculture  143067875.0

In [20]:
#4. Create a new variable with "apply" and "lambda"
df.groupby("loan_amount", group_keys=True).apply(lambda x: x, include_groups=False)

                         id  funded_amount                   activity  \
loan_amount
25.0        22121    674859           25.0                       Pigs
            25119    677920           25.0  Personal Housing Expenses
            27978    680421           25.0     Higher education costs
            44058    696608           25.0     Higher education costs
            46960    699302           25.0  Personal Housing Expenses
...                     ...            ...                        ...
50000.0     631904  1294308        50000.0                Agriculture
            657346  1319479        22500.0                   Services
            659727  1323015        13225.0                       Arts
            660807  1323028        46125.0  Renewable Energy Products
100000.0    70499    722883       100000.0                Agriculture

                         sector  \
loan_amount
25.0        22121   Agriculture
            25119       Housing
            27978     Education
            44058     Education
            46960       Housing
...                         ...
50000.0     631904  Agriculture
            657346     Services
            659727         Arts
            660807       Retail
100000.0    70499   Agriculture

                                                                  use  \
loan_amount
25.0        22121                       to purchase feed for her pigs
            25119     to buy building materials to renovate her home.
            27978   to pay for his second semester and buy a compu...
            44058                   To pay for higher education costs
            46960   to buy vacuum insulated windows, hardwood floo...
...                                                               ...
50000.0     631904  double cashew nut export output and hire about...
            657346  Impact Hub Accra improve its innovation and en...
            659727  expand their retail sales channels and create ...
            660807  to distribute 400 pay-as-you-go solar systems ...
100000.0    70499   create more than 300 jobs for women and farmer...

                   country_code        country  \
loan_amount
25.0        22121            PH    Philippines
            25119            MN       Mongolia
            27978            KH       Cambodia
            44058            KH       Cambodia
            46960            MN       Mongolia
...                         ...            ...
50000.0     631904           CI  Cote D'Ivoire
            657346           GH          Ghana
            659727           UG         Uganda
            660807           PK       Pakistan
100000.0    70499            HT          Haiti

                                                    region currency  \
loan_amount
25.0        22121   Dipolog-Katipunan, Zamboanga del Norte      PHP
            25119                                  Erdenet      MNT
            27978                               Phnom Penh      KHR
            44058        Phnom Penh, Ksach Kandal District      KHR
            46960                              Ulaanbaatar      MNT
...                                                    ...      ...
50000.0     631904                                   Kolia      USD
            657346                                   Accra      USD
            659727                                 Kampala      USD
            660807                                 Karachi      USD
100000.0    70499                                Les Cayes      USD

                    partner_id                posted_time  \
loan_amount
25.0        22121        126.0  2014-02-22 02:09:07+00:00
            25119         42.0  2014-02-28 04:56:37+00:00
            27978        106.0  2014-03-07 01:45:02+00:00
            44058        204.0  2014-04-11 05:00:54+00:00
            46960         42.0  2014-04-18 08:38:35+00:00
...                        ...                        ...
50000.0     631904       478.0  2017-05-08 17:04:17+00:00
            657346       521.0  2017-06-14 08:07:03+00:00
            659727       532.0  2017-06-19 23:16:12+00:00
            660807       536.0  2017-06-20 00:01:21+00:00
100000.0    70499        315.0  2014-06-10 19:25:02+00:00

                               disbursed_time                funded_time  \
loan_amount
25.0        22121   2014-01-24 08:00:00+00:00  2014-02-25 03:09:19+00:00
            25119   2014-02-27 08:00:00+00:00  2014-03-04 03:29:26+00:00
            27978   2014-02-11 08:00:00+00:00  2014-03-09 02:15:26+00:00
            44058   2014-03-21 07:00:00+00:00  2014-04-22 19:43:40+00:00
            46960   2014-04-17 07:00:00+00:00  2014-04-21 02:15:44+00:00
...                                       ...                        ...
50000.0     631904  2017-04-08 07:00:00+00:00  2017-05-18 05:06:35+00:00
            657346  2017-09-11 07:00:00+00:00                        NaN
            659727  2017-08-31 07:00:00+00:00                        NaN
            660807  2017-08-31 07:00:00+00:00                        NaN
100000.0    70499   2014-09-08 07:00:00+00:00  2014-06-19 20:21:04+00:00

                    term_in_months  lender_count  \
loan_amount
25.0        22121              8.0             1
            25119             14.0             1
            27978             14.0             1
            44058             39.0             1
            46960             24.0             1
...                            ...           ...
50000.0     631904            10.0          1706
            657346            48.0           684
            659727            14.0           447
            660807            14.0           805
100000.0    70499             75.0          2986

                                                                 tags  \
loan_amount
25.0        22121                                                 NaN
            25119                                                 NaN
            27978                                       user_favorite
            44058                                       user_favorite
            46960                      volunteer_pick, volunteer_like
...                                                               ...
50000.0     631904  user_favorite, user_favorite, #Vegan, #Job Cre...
            657346  user_favorite, user_favorite, #Biz Durable Ass...
            659727  user_favorite, #Job Creator, #Technology, #Wom...
            660807  #Eco-friendly, #Technology, user_favorite, #Jo...
100000.0    70499   user_favorite, user_favorite, user_favorite, u...

                   borrower_genders repayment_interval        date
loan_amount
25.0        22121            female          irregular  2014-02-22
            25119            female            monthly  2014-02-28
            27978              male            monthly  2014-03-07
            44058            female            monthly  2014-04-11
            46960              male            monthly  2014-04-18
...                             ...                ...         ...
50000.0     631904           female          irregular  2017-05-08
            657346           female          irregular  2017-06-14
            659727             male          irregular  2017-06-19
            660807           female          irregular  2017-06-20
100000.0    70499            female          irregular  2014-06-10

[671205 rows x 19 columns]

In [21]:
#5 Scaling to large datasets
selected_columns = ['id', 'loan_amount', 'sector', 'country_code', 'currency', 'partner_id', 'date']
df_selected = df[selected_columns]
display(df_selected.head())

,id,loan_amount,sector,country_code,currency,partner_id,date
0,653051,300.0,Food,PK,PKR,247.0,2014-01-01
1,653053,575.0,Transportation,PK,PKR,247.0,2014-01-01
2,653068,150.0,Transportation,IN,INR,334.0,2014-01-01
3,653063,200.0,Arts,PK,PKR,247.0,2014-01-01
4,653084,400.0,Food,PK,PKR,245.0,2014-01-01

In [24]:
#6 Calculate 'unfunded_amount' as the difference between 'loan_amount' and 'funded_amount'
df = df.eval('unfunded_amount = loan_amount - funded_amount')

# 'funded_ratio' the ratio of 'funded_amount' to 'loan_amount'
df = df.eval('funded_ratio = funded_amount / loan_amount')
display(df[['loan_amount', 'funded_amount', 'unfunded_amount', 'funded_ratio']].head())

   loan_amount  funded_amount  unfunded_amount  funded_ratio
0        300.0          300.0              0.0           1.0
1        575.0          575.0              0.0           1.0
2        150.0          150.0              0.0           1.0
3        200.0          200.0              0.0           1.0
4        400.0          400.0              0.0           1.0